services:
  deepdrop-sfe:
    build: .
    image: deepdrop-sfe:latest
    container_name: deepdrop-sfe-app
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
    restart: unless-stopped
